### ISSUE TITLE
Liquidation as Bonus Moon

### ISSUE THREAD

**Issue by thundershocker1** [JackEhttack/DiminishingReturns#12]
For some reason, Liquidation was listed as a bonus moon. Would it be possible for you to create a blacklist of moons that can't become bonus moons

**Comment by JackEhttack** [comment]
I was going to try a clever solution that blacklisted moons if they don't have an actual level but figure it'll just be easier to check if `levelID != 11` and to remove that line of code when (or if) Liquidation is released. Patch will be released in the next major update.
