### ISSUE TITLE
Company lets you Infinity regenerate returns

### ISSUE THREAD

**Issue by VanilaBOI** [JackEhttack/DiminishingReturns#13]
When you go to the company at the end of a quota, it counts as a day so the the moons have a day to regen, which is fine and I really like it that way.
But when you go to the company while you still have days left, the days counter doesn't go down but it still counts as a day of regen for the moons.
(if your wondering why you would go early to the company, I have BuyRateSettings installed)

**Comment by thundershocker1** [comment]
I was about to comment on the same issue. Hopefully, they respond.

**Comment by JackEhttack** [comment]
Sorry for the late response, I've been busy with university.

```c#
public void ReplenishMoons()
   {
      /* Don't replenish if you are visiting the company moon. */
      if (StartOfRound.Instance.currentLevel.levelID == 3) return;
      [...]
   }
```

I'll release an update that resolves this and the other bug involving Liquidation as a bonus moon shortly.
