### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AdamHarney** [JackEhttack/DiminishingReturns#2]
I'm not having any issues with this mod bug wise, but can you make the discounted prices for the moons an option in the config instead of being mandatory?

**Comment by JackEhttack** [comment]
Funnily enough you're wrong about your request not being a bug report.

There was a config option to allow you to modify the discount but due to a bug the option doesn't show.

```
bonusChance = cfg.Bind(
            "General",
            "BonusChance",
            0.5f,
            "The chance of a bonus moon appearing per day.");

moonDiscount = cfg.Bind(
            "General",
            "BonusChance", // duplicated key, doesn't show option in config
            0.5f,
            "A discount applied to the price of moons, to make up for diminishment.");
```

I've fixed it and will send out an update in the next few hours, cheers.
