### ISSUE TITLE
Can't Land on new save

### ISSUE THREAD

**Issue by VanilaBOI** [JackEhttack/DiminishingReturns#4]
If I start one Save and then quit out of that one and start another one I can't land on any moon beside the one that is diminished(and sometimes not at all).

I've also realized that the calculations of the diminishing returns happen a bit weird.
When land on a moon the tracker already says that the moon has been diminished, even tough it still has the full amount, which is fine I don't care too much about that.
But when you go back into Orbit it says that it already has regenerated some of the diminished % (Ex. It was dimished to 20% on the moon and is back at 40%, once back in Orbit)
Which is reflected by how when you land again, it has it's Scrap diminished by -60% instead of -80%.
I'd say it should be moved back one step so while the ship is on the moon it doesn't say anything, until you're back in orbit where it would say the diminished amount, without the regenerated %.

Also also I can't set the the "MaxDiminish" value to 1, I can only use decimals.

**Comment by AdamHarney** [comment]
I am also having this problem of being unable to land.

**Comment by JackEhttack** [comment]
> If I start one Save and then quit out of that one and start another one I can't land on any moon beside the one that is diminished(and sometimes not at all).
Whoop. I didn't test the netcode for the mod thoroughly enough. I'll start working on a fix and try to have it out by the end of the day.

> When land on a moon the tracker already says that the moon has been diminished, even tough it still has the full amount, which is fine I don't care too much about that.
That's intentional, but I do agree it's a bit weird.

> But when you go back into Orbit it says that it already has regenerated some of the diminished % (Ex. It was dimished to 20% on the moon and is back at 40%, once back in Orbit)
This is "intentional" behaviour, but also weird.

I'll make it so that the current moon is either excluded from being replenished when leaving or just diminish it after the rest of the moons are diminished.
