### ISSUE TITLE
diminished Returns stays on play session

### ISSUE THREAD

**Issue by VanilaBOI** [JackEhttack/DiminishingReturns#6]
With the Networking problem crushed comes a new problem.
When you play and start diminishing moons and switch save files, the diminished returns are kept across them.
But when you restart the game all saves have them set to zero again.

So it is saved on the players session and not the save states.

**Comment by JackEhttack** [comment]
When loading old DiminishingReturns data from the save file I forgot to clear the old data before loading in the new data. It will now do that in the next update.

I discovered an additional bug that results in the most recently diminished moon to not be saved onto the file. Two birds with one Github issue. Thank you again @VanilaBOI.
