### ISSUE TITLE
Incompatible with Advanced Company and WeatherRegistry

### ISSUE THREAD

**Issue by VanilaBOI** [JackEhttack/DiminishingReturns#7]
When I have either Advanced Company or WeatherRegistry, there is no diminished scrap.

Funny Enough it's the two mods that have a say in loot amount.

**Comment by JackEhttack** [comment]
Advanced Company appears to have been deleted by it's developer, can't help with that.

As for WeatherRegistry, the mod appears to not respect the scrapAmountMultiplier and scrapValueMultiplier and just overwrites the value with it's own. I just need to adjust the function for this mod that messes with these values to after their code and it should work just fine.

**Comment by JackEhttack** [comment]
This was a bit more complicated than expected but as a side effect to implementing this made it so DiminishingReturns only needs BepInEx as a dependency now. It should work with WeatherRegistry and possibly AdvancedCompany, maybe.

**Comment by VanilaBOI** [comment]
Wow you are amazing, I just tested it and it works for WeatherRegistry and Advanced Company.
